name: Summarize Results

on:
  workflow_run:
    workflows: ["TSP Test 1", "TSP Test 2", "TSP Test 3"]
    types:
      - completed

jobs:
  summarize:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: results/

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run summarizer
        run: python summarize.py

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: results.txt
