name: TSP Test 3

on:
  repository_dispatch:
    types: [trigger-test3]

jobs:
  run-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test script
        run: python -u _tests.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test3-results-${{ github.event.client_payload.run_number }}
          path: results.txt
      
      - name: Trigger summarization
        if: success()
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: summarize
          client-payload: '{"run_number": "${{ github.event.client_payload.run_number }}"}'
