name: TSP Test 2

on:
  workflow_run:
    workflows: ["TSP Test 1"]
    types: [completed]

jobs:
  run-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test script
        run: python tests.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test2-results
          path: results.txt
