name: TSP Test 1
run-name: TSP Test 1

on:
  push:
    branches: [main]

jobs:
  run-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test script
        run: python -u _tests.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test1-results-${{ github.run_number }}
          path: results.txt

      - name: Trigger test 3
        if: success()
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-test3
          client-payload: '{"run_number": "${{ github.run_number }}"}'
